# Generated by Django 3.2 on 2021-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
